### PR TITLE
Enable  Hyperwallet  SDK support  Proxy mode

### PR DESCRIPTION
**Pull request by fankun**
For proxy model issue, we’d like to high light below changes. Please confirm that we can modify source code in this way before creating a pull request.
 
Change 1. We removed ‘cc.protea.foundation.http’ in Hyperwallet java-sdk POM dependence .  As the class ‘cc.protea.util.http.Request’ didn’t support proxy model.
So we copy all source code from ‘cc.protea.foundation.http’ and overwrite the class ‘cc.protea.util.http.Request’.
Change 2. Modified the class ‘com.hyperwallet.clientsdk.util.HyperwalletApiClient’ in Hyperwallet java-sdk. It is to support  proxy capacity.

### CODE REVIEW

**Comment by wmews-hw** [comment]
Hi @fankun,

This type of change would require more time from us to design and release it. Feel free to make this changes to solve your current problem but for now, I won't be able to make it generally available. Please create a issue so we can vote and prioritize this feature in the upcoming releases.

**Comment by fankun** [comment]
Ok, I agree with you. I will create  an issue for voting this feature. But now how do i  use this feature?  you will release a special snapshot version? Am i right?

**Comment by wmews-hw** [comment]
@fankun feel free to fork it. I can't say for now when this change is going to be made. We will have to consider another HTTP library that supports proxy and it is backward compatible to all our clients. So it will need some investigation.

**Comment by fankun** [comment]
@wmews-hw   I got it, so i just only  fork  it and use it into our production for now before you release a new version with http proxy capacity.

**Pull request closed without merging**
