### PR TITLE
PPPLMER-94004-Fix-for-handling-amount

### PR DESCRIPTION
**Pull request by ramahalingam**
Changes for handling the amount field in SDK

### CODE REVIEW

**Comment by Rrathinasabapath** [comment]
Approving the changes

**Review by Rrathinasabapath — APPROVED** [review]
Verified the changes and approving it.

**Review by jbausch-hw — APPROVED** [review]

**Review by vkorotchenko — APPROVED** [review]
looks good, can we add a test case for when the value is over 1k.

**Review by ddhar-hw — APPROVED** [review]

**Review by vkorotchenko — APPROVED** [review]

**Comment by Rrathinasabapath** [comment]
> looks good, can we add a test case for when the value is over 1k.

I have added a method for values over 1k

**Review by jbausch-hw — APPROVED** [review]

**Review by arao6 — APPROVED** [review]

**Pull request merged**
